In [3]:
import numpy as np

arr1 = np.array([1, 2, 3])
print(arr1)
print(arr1.shape)

[1 2 3]
(3,)


In [4]:
# 1D array
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [13]:
# 2D array
arr2 = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
print(arr2)
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)
2
int64


In [9]:
np.arange(0, 10, 2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
## Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Vectorized Operations

In [19]:
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([10, 20, 30, 40])
print("Addition: ", arr1 + arr2)
print("Subsctraction", arr2 - arr1)
print("Multiplication", arr1 * arr2)
print("Division", arr2 / arr1)

Addition:  [[11 22 33 44]]
Subsctraction [[ 9 18 27 36]]
Multiplication [[ 10  40  90 160]]
Division [[10. 10. 10. 10.]]


In [21]:
# Universal Function
arr1 = np.array([1, 2, 3, 4])
print(np.sqrt(arr1))
print(np.exp(arr1))
print(np.sin(arr1))
print(np.log(arr1))

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]


In [24]:
## array slicing and indexing
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print('Array: \n', arr)
print('Element at row 0 and column 0: ', arr[0,0])

Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 0 and column 0:  1
